name: CI - Lint

on: [pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        uses: rhysd/action-markdown-link-check@v1
        with:
          use-quiet: true
